<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.cyrusimap.org/bugzilla.dtd">

<bugzilla version="3.2.5.1-2"
          urlbase="https://bugzilla.cyrusimap.org/"
          maintainer="Dave McMurtrie &lt;dave64@andrew.cmu.edu&gt;"
>

    <bug>
          <bug_id>3062</bug_id>
          
          <creation_ts>2008-05-15 17:47 EDT</creation_ts>
          <short_desc>cache files become corrupted ( later, sync_server crashes)</short_desc>
          <delta_ts>2010-10-25 18:46:45 EDT</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>Cyrus IMAP</product>
          <component>IMAP</component>
          <version>2.3.x</version>
          <rep_platform>Sun</rep_platform>
          <op_sys>Solaris</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          <priority>P5</priority>
          <bug_severity>bug</bug_severity>
          <target_milestone>Future</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter>cyrus@fiddaman.net</reporter>
          <assigned_to name="Ken Murchison">murch@andrew.cmu.edu</assigned_to>
          <cc>wes@umich.edu</cc>
          

      

      

      
          <long_desc isprivate="0">
            <who name="">cyrus@fiddaman.net</who>
            <bug_when>2008-05-15 17:47:31 EDT</bug_when>
            <thetext>I have a replicated setup and after a while sync_server starts crashing and it crashes repeatedly on restart. Here&apos;s the debug I have so far but I&apos;ve added some debug lines to the code and am waiting for it to crash again.

Once I rsync the stores and remove the old sync log files then it all runs fine for a while and then it starts crashing again.

Core was generated by `sync_server&apos;.
Program terminated with signal 11, Segmentation fault.
[New process 71345    ]
#0  0x0000000100020204 in sync_cacheitem_size (
    cacheitem=0xffffffff97db9528 &lt;Address 0xffffffff97db9528 out of bounds&gt;)
    at sync_commit.c:330
330             cacheitem = CACHE_ITEM_NEXT(cacheitem);
(gdb) print cacheitem
$1 = 0xffffffff97db9528 &lt;Address 0xffffffff97db9528 out of bounds&gt;
(gdb) print cacheitembegin
$3 = 0xffffffff778b22bc &quot; Prestige\&quot; ((\&quot;del philippe\&quot; NIL \&quot;rangely\&quot; \&quot;domain.net\&quot;)) ((\&quot;del philippe\&quot; NIL \&quot;rangely\&quot; \&quot;domain.net\&quot;)) ((\&quot;del philippe\&quot; NIL \&quot;rangely\&quot; \&quot;domain.net\&quot;)) ((NIL NIL \&quot;jagood\&quot; \&quot;domain.co.uk\&quot;)) NIL NIL NIL \&quot;&lt;000901c8a8b9$03fade7f$848e5f90@dnmqfv&gt;\&quot;)&quot;</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <who name="Wes Craig">wes@umich.edu</who>
            <bug_when>2008-10-07 15:06:43 EDT</bug_when>
            <thetext>Looks like a corrupted cache file.  Have you tried reconstructing the user on both backend and replica?</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <who name="">cyrus@fiddaman.net</who>
            <bug_when>2008-10-08 05:01:11 EDT</bug_when>
            <thetext>A reconstruct always fixes this. I usually reconstruct the master and then rsync the replica again. A month or so later another mailbox gets corrupt and the server starts crashing in the same place.

I suspect this is a bug that only affects 64-bit binaries and perhaps only on SPARC or big endian architectures. I have done some intensive memory testing on the machine so am fairly confident about the hardware.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <who name="Wes Craig">wes@umich.edu</who>
            <bug_when>2008-10-08 08:51:59 EDT</bug_when>
            <thetext>Could be.  What version are you running?  2.3.13 will have a few 64-bit changes, and I we&apos;re planning a 64-bit &amp; largefile audit for 2.4.0.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <who name="">cyrus@fiddaman.net</who>
            <bug_when>2008-10-09 10:43:37 EDT</bug_when>
            <thetext>2.3.12 at present.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <who name="Wes Craig">wes@umich.edu</who>
            <bug_when>2008-10-09 10:54:33 EDT</bug_when>
            <thetext>Let&apos;s see if 2.3.13 fixes it.  If not, probably digging into the corrupted file is the thing to do.  This is not a bug in sync_server, per se.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <who name="Wes Craig">wes@umich.edu</who>
            <bug_when>2008-11-24 14:15:07 EDT</bug_when>
            <thetext>If 2.3.13 doesn&apos;t fix this problem for you, please reopen this or another bug with a report.  Thanks.</thetext>
          </long_desc>
      
      

    </bug>

</bugzilla>