<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.cyrusimap.org/bugzilla.dtd">

<bugzilla version="3.2.5.1-2"
          urlbase="https://bugzilla.cyrusimap.org/"
          maintainer="Dave McMurtrie &lt;dave64@andrew.cmu.edu&gt;"
>

    <bug>
          <bug_id>3666</bug_id>
          
          <creation_ts>2012-04-05 06:09 EDT</creation_ts>
          <short_desc>Initial Replication run locks with &quot;Failed to upload file&quot;</short_desc>
          <delta_ts>2012-10-19 16:49:12 EDT</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>Cyrus IMAP</product>
          <component>Replication</component>
          <version>2.4.13</version>
          <rep_platform>PC</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          <priority>P3</priority>
          <bug_severity>bug</bug_severity>
          <target_milestone>2.5-next</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Alan Robertson">alanjrobertson@gmail.com</reporter>
          <assigned_to name="Bron Gondwana">brong@fastmail.fm</assigned_to>
          
          <qa_contact name="The Cyrus Bugzilla List">cyrus-bugzilla@lists.andrew.cmu.edu</qa_contact>

      

      

      
          <long_desc isprivate="0">
            <who name="Alan Robertson">alanjrobertson@gmail.com</who>
            <bug_when>2012-04-05 06:09:18 EDT</bug_when>
            <thetext>First replication run between a populated server (hundreds of gigs) and a new replica locks with the message &quot;syncserver[14260]: Failed to upload file&quot;.

No message at the master side from sync_client - it just hangs. No further data is synchronised. 

Killing the sync_client process and re-running always succeeds the second time till it happens again.

Sync_client on the master is running as:

/usr/cyrus/bin/sync_client -v -S x.x.x.x -u -f mailboxlist</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <who name="Bron Gondwana">brong@fastmail.fm</who>
            <bug_when>2012-10-19 16:38:49 EDT</bug_when>
            <thetext>    /* XXX - write to a temporary file then move in to place! */
    *fname = dlist_reserve_path(part, guid);

    file = fopen(*fname, &quot;w+&quot;);
    if (!file) {
&gt;-------syslog(LOG_ERR, &quot;Failed to upload file %s&quot;, message_guid_encode(guid));


The problem is almost certainly that your spool directory doesn&apos;t exist.

const char *dlist_reserve_path(const char *part, struct message_guid *guid)
{
    static char buf[MAX_MAILBOX_PATH];
    snprintf(buf, MAX_MAILBOX_PATH, &quot;%s/sync./%lu/%s&quot;,
&gt;-------&gt;-------  config_partitiondir(part), (unsigned long)getpid(),
&gt;-------&gt;-------  message_guid_encode(guid));
    cyrus_mkdir(buf, 0755);
    return buf;
}

Which is fine - so not only did the directory not exist, the permissions must be wrong.  I will add syslogging in there so we know if cyrus_mkdir fails.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <who name="Bron Gondwana">brong@fastmail.fm</who>
            <bug_when>2012-10-19 16:49:12 EDT</bug_when>
            <thetext>OK, I&apos;ve added more debugging so you will see that you have incorrect permissions on the replica end at startup, and I consider this resolved.  It will be in 2.5.</thetext>
          </long_desc>
      
      

    </bug>

</bugzilla>